# Generated by Django 5.2 on 2025-04-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Product Title')),
                ('price', models.IntegerField(default=0, verbose_name='Product Price')),
            ],
        ),
    ]
